export const allProducts = [
    {
      id: "food-basket",
      name: "Essential Food Basket",
      description: "A large basket filled with pantry essentials to keep a family fed for a week.",
      price: 79.99,
      image: "https://images.unsplash.com/photo-1579113800032-c38bd7635818?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      category: "Food",
    },
    {
      id: "winter-jacket",
      name: "Winter Jacket",
      description: "Stay warm with this insulated winter jacket, essential for cold weather.",
      price: 69.99,
      image: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      category: "Clothing",
    },
    {
      id: "bedding-set",
      name: "Comforter Bedding Set",
      description: "Cozy bedding set with sheets, pillowcases, and a warm comforter.",
      price: 89.99,
      image: "https://images.unsplash.com/photo-1629949009765-28a429ff37f6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      category: "Household",
    },
    {
      id: "gift-card",
      name: "Grocery Gift Card",
      description: "A gift card for purchasing groceries at major supermarkets.",
      price: 50.00,
      image: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      category: "Gift Cards",
    },
    {
      id: "toiletries-kit",
      name: "Essential Toiletries Kit",
      description: "Complete kit with shampoo, soap, toothpaste, and other personal care items.",
      price: 45.99,
      image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      category: "Personal Care",
    },
    {
      id: "kitchen-set",
      name: "Basic Kitchen Set",
      description: "Essential pots, pans, and utensils for preparing meals.",
      price: 129.99,
      image: "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      category: "Household",
    },
    {
      id: "blanket",
      name: "Warm Fleece Blanket",
      description: "Soft, warm blanket for cold nights.",
      price: 35.99,
      image: "https://images.unsplash.com/photo-1600369672770-985fd30001c2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      category: "Household",
    },
    {
      id: "backpack",
      name: "Multi-purpose Backpack",
      description: "Durable backpack for everyday use or school.",
      price: 49.99,
      image: "https://images.unsplash.com/photo-1622560480605-d83c661b4a12?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      category: "Clothing",
    },
    {
      id: "baby-essentials",
      name: "Baby Essentials Kit",
      description: "Diapers, wipes, formula, and other necessities for infants.",
      price: 85.99,
      image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      category: "Baby",
    },
    {
      id: "school-supplies",
      name: "School Supplies Bundle",
      description: "Notebooks, pens, pencils, and other essential school items.",
      price: 55.99,
      image: "https://images.unsplash.com/photo-1588075592446-265bad1d861c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      category: "Education",
    },
  ];